name: Commit Check

on:
  schedule:
    - cron: "00 15 * * 0" # 매주 일요일 15:00 UTC (서울 기준 00:00) '00 15 * * *'

jobs:
  check-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check commits and send message
        run: python3 main.py
